[phases.setup]
nixPkgs = ["python313", "gcc"]
aptPkgs = ["libmariadb-dev", "libmariadb-dev-compat", "pkg-config"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]
