[phases.setup]
nixPkgs = ["python313", "gcc", "pkg-config", "mariadb-connector-c"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]
